---
galaxy_info:
  author: Ansible Automation
  description: Common system configuration for Kubernetes nodes
  company: Homelab
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - "24.04"
  galaxy_tags:
    - system
    - kubernetes
    - ubuntu

dependencies: []