---
# Ansible Galaxy requirements for this project
# Currently no external roles required - all roles are custom built

# Example of external roles that might be useful:
# - name: geerlingguy.docker
#   version: ">=6.0.0"
# - name: kubernetes-sigs.kubespray
#   version: ">=2.20.0"

# Required collections for this project
collections:
  - name: ansible.posix
    version: ">=1.3.0"
  - name: community.general
    version: ">=4.0.0"