---
galaxy_info:
  author: Ansible Automation
  description: Kubernetes components (kubeadm, kubelet, kubectl) installation
  company: Homelab
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - "24.04"
  galaxy_tags:
    - kubernetes
    - kubeadm
    - kubelet
    - kubectl

dependencies: []