---
galaxy_info:
  author: Ansible Automation
  description: containerd container runtime installation and configuration
  company: Homelab
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - "24.04"
  galaxy_tags:
    - container
    - containerd
    - kubernetes
    - cri

dependencies: []